"""add hos_total_reinvest_dividend to holding_snapshot

Revision ID: 004_add_hos_total_reinvest_dividend
Revises: 003_add_risk_free_rate
Create Date: 2026-02-24 15:35:38.992200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_add_hos_total_reinvest_dividend'
down_revision: Union[str, Sequence[str], None] = '003_add_risk_free_rate'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding_snapshot', sa.Column('hos_total_reinvest_dividend', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holding_snapshot', 'hos_total_reinvest_dividend')
    # ### end Alembic commands ###
